apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eric-adp-gui-aggregator-service.name" . }}-log-config
  labels:
  {{- include "eric-adp-gui-aggregator-service.labels" . | nindent 4 }}
  annotations:
  {{- include "eric-adp-gui-aggregator-service.annotations" . | nindent 4 }}
data:
  logcontrol.json: |
    [
      {
        "container": "main",
        "severity": "{{ .Values.configuration.logging.defaultLogLevel }}"
      }
    ]