{{- if .Values.global -}}
{{- if and .Values.global.networkPolicy .Values.networkPolicy -}}
{{- if and .Values.global.networkPolicy.enabled .Values.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: {{ .Capabilities.APIVersions.Has "networking.k8s.io/v1" | ternary "networking.k8s.io/v1" "networking.k8s.io/v1beta1" }}
metadata:
  name: {{ template "eric-adp-gui-aggregator-service.name" . }}
  annotations:
    {{- include "eric-adp-gui-aggregator-service.annotations" . | nindent 4 }}
  labels:
    {{- include "eric-adp-gui-aggregator-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: {{ template "eric-adp-gui-aggregator-service.name" . }}
  policyTypes:
  - Ingress
  ingress:
  # ALLOW traffic from external clients
  - from:
    - namespaceSelector: {}
      podSelector: {}
    ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
    {{- if .Values.metrics.enabled }}
    - port: {{ .Values.metrics.port }}
      protocol: TCP
    {{- end -}}
    {{- if .Values.authorizationProxy.enabled }}
    - port: 8888
      protocol: TCP
    {{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
