{{- if ne (include "eric-adp-gui-aggregator-service.rolekind" .) "" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "eric-adp-gui-aggregator-service.serviceAccountName" . }}-{{ template "eric-adp-gui-aggregator-service.rki" . }}-{{ .Values.securityPolicy.rolename }}-sp
  labels:
    {{- include "eric-adp-gui-aggregator-service.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-adp-gui-aggregator-service.annotations" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "eric-adp-gui-aggregator-service.serviceAccountName" . }}
roleRef:
  kind: {{ include "eric-adp-gui-aggregator-service.rolekind" . }}
  name: {{ .Values.securityPolicy.rolename }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
