{{- $global := fromJson (include "eric-adp-gui-aggregator-service.global" .) -}}
{{- if and $global.security.tls.enabled .Values.configuration.faultIndications.enabled }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: {{ include "eric-adp-gui-aggregator-service.name" . }}-fi-api-client-cert
  labels:
    {{- include "eric-adp-gui-aggregator-service.labels" . | nindent 4 }}
  annotations:
    {{- include "eric-adp-gui-aggregator-service.annotations" . | nindent 4 }}
spec:
  kubernetes:
    generatedSecretName: {{ include "eric-adp-gui-aggregator-service.name" . }}-fi-api-client-cert
  certificate:
    subject:
      cn: {{ include "eric-adp-gui-aggregator-service.name" . }}
    issuer:
      reference: {{ .Values.configuration.dependencies.faultHandler.hostname }}-fi-server-client-ca
    subjectAlternativeName:
      populateKubernetesDns: false
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: true

{{- end }}
