global:
  security:
    tls:
      enabled: false

service:
  type: NodePort
  endpoints:
    http:
      tls:
        enforced: optional
        verifyClientCertificate: optional

uiconfig:
  protocol: http

log:
  streamingMethod: indirect

configuration:
  faultIndications:
    enabled: false

metrics:
  enabled: false

manualconfig:
  apps:
    - displayName: "Manualconfig Wrapper Application"
      version: "1.0.0"
      name: "manual-wrapper"
      groupNames: ["mg"]
      type: "euisdk"
      module: "wrapper-app"
      route: "manual-wrapper"
      options:
        url: "https://adp.ericsson.se/marketplace"
        query: ""
  groups:
    - displayName: "Manualconfig Group"
      version: "1.0.0"
      name: "mg"
      type: "product"
  groupMappings:
    - group: mock-group
      apps:
        - charts
