version: '2.1'

services:
  seleniumhub:
    container_name: docker_frontend_seleniumhub_${BUILD_TAG}
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/selenium/hub:4.18.1 # update this regularly
    shm_size: 1g
    logging:
      driver: 'json-file'
    healthcheck:
      test: ['CMD', 'true'] # disable the healthcheck

  nodechrome:
    container_name: docker_frontend_nodechrome_${BUILD_TAG}
    image: armdocker.rnd.ericsson.se/dockerhub-ericsson-remote/selenium/node-chrome:122.0 # update this regularly
    links:
      - seleniumhub:hub
    depends_on:
      - seleniumhub
    environment:
      - SE_EVENT_BUS_HOST=seleniumhub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
    volumes:
      - ../:/local/app
    shm_size: 2g
    logging:
      driver: 'json-file'

    # it can be only started on a repository which has been initalized via npm install* command
  mock-server:
    container_name: docker_frontend_mock-server_${BUILD_TAG}
    image: armdocker.rnd.ericsson.se/proj-adp-cicd-drop/adp-nodejs-lts-builder-image:20.12.2-0
    command: >
      bash -c "
      cd /local/app &&
      npm run build:selenium &&
      npm run build:mocks &&
      npm run start:built:frontend"
    volumes:
      - ../:/local/app
    environment:
      - TEST_MODE=mock
    shm_size: 1g
    user: '${USER_ID}:${GROUP_ID}'
    logging:
      driver: 'json-file'

    # it can be only started on a repository which has been initalized via npm install* command
  test-mock:
    container_name: docker_frontend_test-mock_${BUILD_TAG}
    image: armdocker.rnd.ericsson.se/proj-adp-cicd-drop/adp-nodejs-lts-builder-image:20.12.2-0
    command: >
      bash -c "
      npx wait-on --log -i 2000 -t 600000 http-get://seleniumhub:4444 http://mock-server:8080/ui &&
      cd /local/app &&
      npm run e2e:frontend:docker ;
      TEST_STATUS=$$? ;
      npm run e2e:frontend:generateReport ;
      if [[ $$TEST_STATUS -ne 0 ]]; then
      TEST_STATUS=2 ;
      fi ;
      exit $$TEST_STATUS"
    links:
      - seleniumhub
      - mock-server
    depends_on:
      - nodechrome
      - mock-server
    environment:
      - BASE_URL=http://mock-server:8080/ui
      - SELENIUM_HOST=seleniumhub
      - SELENIUM_PORT=4444
      - DOWNLOAD_DIRECTORY_PATH=${DOWNLOAD_PATH}
      - TEST_MODE=mock
      - LANG=C.UTF-8
    volumes:
      - ../:/local/app
    shm_size: 1g
    user: '${USER_ID}:${GROUP_ID}'
    logging:
      driver: 'json-file'
