apiVersion: v1
kind: Service
metadata:
  name: {{ include "domain-ui-generic.name" . }}-http
  labels:
    dui-generic: {{ include "domain-ui-generic.name" . }}
    app.kubernetes.io/name: {{ include "domain-ui-generic.name" . }}
    app.kubernetes.io/version: {{ .Values.productInfo.version }}
    {{- if .Values.labels -}}
    {{- range $name, $config := .Values.labels }}
    {{ $name }}: {{ tpl $config $ }}
    {{- end }}
    {{- end }}
  annotations:
  {{- if and .Values.global.security.tls.enabled }}
    projectcontour.io/upstream-protocol.tls: {{ .Values.service.port | quote }}
  {{- end }}
  {{- if .Values.contextRoot }}
    ui.ericsson.com/config-context: {{ .Values.contextRoot }}
  {{- end }}
  {{- if .Values.ingress.enabled }}
    ui.ericsson.com/external-baseurl: http://{{.Values.ingress.hostname}}{{ .Values.ingress.path }}/
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    dui-generic: {{ include "domain-ui-generic.name" . }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      {{- if .Values.global.security.tls.enabled }}
      name: http-tls
      {{- else }}
      name: http
      {{- end }}
