{{- $global := fromJson (include "ci.global" .) -}}
{{- $accessMgmt := index .Values "eric-sec-access-mgmt" }}
{{- if $global.security.tls.enabled }}
apiVersion: siptls.sec.ericsson.com/v1
kind: InternalCertificate
metadata:
  name: eric-adp-gui-aggregator-service-ingress-external-server-cert
spec:
  kubernetes:
    generatedSecretName: eric-adp-gui-aggregator-service-ingress-external-server-cert
    secretType: tls
  certificate:
{{- if and $accessMgmt.adpIamUserName $accessMgmt.adpIamUserPwd }}
    subjectAlternativeName:
      populateKubernetesDns: false
    dns:
      - gas-ingress-host-name
      - {{ $accessMgmt.ingress.hostname }}
    subject:
      cn: {{ $accessMgmt.ingress.hostname }}
{{- else }}
    subject:
      cn: gas-ingress-host-name
{{- end }}
    extendedKeyUsage:
      tlsClientAuth: true
      tlsServerAuth: true
    validity:
      overrideTtl: 2592000 # 30 days in seconds
{{- end }}
