{{- $accessMgmt := index .Values "eric-sec-access-mgmt" }}
{{- $global := fromJson (include "ci.global" .) -}}
{{- if and  $accessMgmt.adpIamUserName $accessMgmt.adpIamUserPwd }}
apiVersion: batch/v1
kind: Job
metadata:
  name: eric-adp-gui-aggregator-service-iam-management-hook
  labels:
  annotations:
    "helm.sh/hook": post-install, post-upgrade, post-rollback
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      imagePullSecrets:
        - name: arm-pullsecret
      restartPolicy: OnFailure
      containers:
        - name: iam-manager-hook
          image: armdocker.rnd.ericsson.se/proj-ldc/common_base_os_release/sles:5.6.0-11
          imagePullPolicy: "IfNotPresent"
          env:
          - name: IAM_ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: {{ $accessMgmt.statefulset.adminSecret }}
                key: kcadminid
          - name: IAM_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $accessMgmt.statefulset.adminSecret }}
                key: kcpasswd
          - name: KEYCLOAK_HOSTNAME
            value: {{ $accessMgmt.ingress.hostname }}
          - name: KEYCLOAK_PORT
            value: '443'
          - name: REALM_NAME
            value: {{ $accessMgmt.adpIamRealm }}
          - name: USER_NAME
            value: {{ $accessMgmt.adpIamUserName }}
          - name: USER_PASSWORD
            value: {{ $accessMgmt.adpIamUserPwd }}
          command:
          - "/mnt/scripts/createUser.sh"
          volumeMounts:
          - name: create-user-script-volume
            mountPath: /mnt/scripts
          - name: cacert-volume
            mountPath: /mnt/certs
          securityContext:
            allowPrivilegeEscalation: true
            readOnlyRootFilesystem: false # kecloak client does write on the root file system
            runAsNonRoot: false
            runAsUser: 0
            capabilities:
              drop:
              - all
      volumes:
      - name: cacert-volume
        secret:
          secretName: eric-sec-sip-tls-trusted-root-cert
          items:
            - key: ca.crt
              path: iam/ca.crt
      - name: create-user-script-volume
        configMap:
          name: create-iam-user-in-realm
          defaultMode: 0777
{{- end }}