export default {
  LAUNCHER: 'launcher',
  PRODUCT_TYPE: 'product',
  SYSTEM_TYPE: 'system',
  CATEGORY_TYPE: 'category',
  EXTERNAL_TYPE: 'external',
  EUISDK_TYPE: 'euisdk',
  LAST_OPENED: 'lastOpened',
  IS_FAVORITE: 'isFavorite',
  ALL_APPS: 'all',
  LANDING_CARD_COUNT: 8,
  SHOW_FAVORITES_ONLY: 'favorites',
  PRODUCT_NAME: 'productName',
  NAME_RANK: 5,
  TAGS_RANK: 3,
  SECONDARY_INFO_RANK: 2,
  DESC_RANK: 1,
  ENTER_KEY: 'Enter',
  ESCAPE_KEY: 'Escape',
  SPACE_KEY: ' ',
  F_KEY: 'f',
  I_KEY: 'i',
  FAVORITE_STATE: {
    FAVORITE: 'favorite',
    NOT_FAVORITE: 'not-favorite',
    PARTIALLY_FAVORITE: 'partially-favorite',
  },
  FAVORITE_COLOR: 'var(--yellow-43)',
  COMPACT_VIEW_BREAKPOINT: 680,
  UI_SETTINGS_CHANGE: 'ui-settings-change',
  FOCUS_SEARCH_BAR_EVENT: 'focus:searchBar',
  LOCATION_CHANGE_EVENT: 'location:change',
  VIEW_TYPE: {
    TILE: 'tile',
    LIST: 'list',
  },
  GROUPPING_TYPE: {
    CATEGORY: 'category',
    ALPHABETICAL: 'alphabetical',
  },
  CONFIG_LOCATION: '/deployment-config/frontend-config.json',
  DEFAULT_TITLE: 'Ericsson Portal',
  APP_META: 'AppMeta',
  GROUP_META: 'GroupMeta',
  COMMON_NAMESPACE: 'adp-ui-common',
  DEFAULT_NAMESPACE: 'gui-aggregator-service',
  USERNAME_RESPONSE_KEY: 'username',
  LAST_LOGIN_TIME_RESPONSE_KEY: 'lastLoginTime',
};
