{{ if .Values.global.networkPolicy.enabled -}}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: deny-ingress-in-namespace-networkpolicy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  ingress: []
{{- end }}
